In [10]:
import numpy as np
import pandas as pd

In [19]:
df = pd.read_csv('train_data.csv')
df
df.tail(10)

,ID,DR,NORMAL,MH,ODC,TSLN,ARMD,DN,MYA,BRVO,...,CRVO,CNV,RS,ODE,LS,CSR,HTR,ASR,CRS,OTHER
1754,im0381,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,1,0,1
1755,im0382,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,0
1756,im0383,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1757,im0384,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1758,im0385,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1759,im0395,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1760,im0396,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
1761,im0398,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,0
1762,im0400,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1763,im0401,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1

In [15]:
df = pd.read_csv('val_data.csv')
df

,ID,DR,NORMAL,MH,ODC,TSLN,ARMD,DN,MYA,BRVO,...,CRVO,CNV,RS,ODE,LS,CSR,HTR,ASR,CRS,OTHER
0,aria_c_28_19,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,aria_c_36_4,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,aria_c_40_b_14,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,aria_c_23_23,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,aria_c_43_1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
439,im0373,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
440,im0377,0,0,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,0
441,im0397,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
442,im0399,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
443,im0402,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

ID : Il s'agit probablement d'un identifiant unique pour chaque entrÃ©e dans votre ensemble de donnÃ©es. Cet ID est gÃ©nÃ©ralement utilisÃ© pour rÃ©fÃ©rencer chaque enregistrement de maniÃ¨re unique.

DR : Cette colonne pourrait reprÃ©senter une catÃ©gorie ou un label liÃ© Ã  une condition mÃ©dicale liÃ©e Ã  la rÃ©tinopathie diabÃ©tique (DR). Les valeurs de cette colonne indiqueraient probablement si un patient a ou non cette condition.

NORMAL : Cette colonne peut indiquer si l'image de l'Å“il est normale, c'est-Ã -dire si elle ne prÃ©sente aucune anomalie ou pathologie.

MH : Il s'agit peut-Ãªtre d'une abrÃ©viation de "Macular Hole" (trou maculaire). Cette colonne pourrait indiquer la prÃ©sence ou l'absence de cette condition dans l'Å“il.

ODC : Cette abrÃ©viation pourrait faire rÃ©fÃ©rence Ã  une condition oculaire spÃ©cifique. Sans plus d'informations, il est difficile de prÃ©ciser Ã  quoi cela correspond exactement.

TSLN : Cette colonne pourrait Ã©galement reprÃ©senter une condition oculaire spÃ©cifique. Il serait nÃ©cessaire d'avoir plus d'informations pour l'interprÃ©ter correctement.

ARMD : Il s'agit probablement d'une abrÃ©viation pour "Age-Related Macular Degeneration" (dÃ©gÃ©nÃ©rescence maculaire liÃ©e Ã  l'Ã¢ge). Cette colonne pourrait indiquer la prÃ©sence ou l'absence de cette condition.

DN : Cette abrÃ©viation pourrait faire rÃ©fÃ©rence Ã  une condition oculaire spÃ©cifique. Une explication plus dÃ©taillÃ©e serait nÃ©cessaire pour en savoir plus.

MYA : De mÃªme, cette colonne pourrait reprÃ©senter une condition oculaire spÃ©cifique. Il serait important de comprendre la signification de cette abrÃ©viation.

BRVO : Cette colonne peut indiquer la prÃ©sence ou l'absence d'une occlusion de la veine rÃ©tinienne (BRVO - Branch Retinal Vein Occlusion).

ODP : Cette colonne pourrait reprÃ©senter une occlusion de la veine rÃ©tinienne (ODP - Ocular Dominance).

CRVO : De maniÃ¨re similaire Ã  BRVO, cette colonne peut indiquer la prÃ©sence ou l'absence d'une occlusion de la veine rÃ©tinienne centrale (CRVO - Central Retinal Vein Occlusion).

CNV : Cette abrÃ©viation pourrait faire rÃ©fÃ©rence Ã  une condition liÃ©e Ã  une nÃ©ovascularisation choroÃ¯dienne (CNV - Choroidal Neovascularization).

RS : Cette colonne pourrait reprÃ©senter une condition oculaire spÃ©cifique. Une description plus dÃ©taillÃ©e serait nÃ©cessaire.

ODE : De mÃªme, cette colonne pourrait indiquer la prÃ©sence ou l'absence d'une condition oculaire particuliÃ¨re.

LS : Cette abrÃ©viation pourrait faire rÃ©fÃ©rence Ã  une condition oculaire spÃ©cifique. Plus d'informations seraient nÃ©cessaires pour une interprÃ©tation prÃ©cise.

CSR : Cette colonne pourrait indiquer la prÃ©sence ou l'absence d'une condition appelÃ©e "Central Serous Retinopathy" (CSR).

HTR : Cette colonne pourrait reprÃ©senter une condition oculaire spÃ©cifique. Il serait important de connaÃ®tre la signification de cette abrÃ©viation.

ASR : De mÃªme, cette colonne pourrait indiquer la prÃ©sence ou l'absence d'une condition oculaire particuliÃ¨re.

CRS : Cette colonne pourrait reprÃ©senter une condition oculaire spÃ©cifique. Une description plus dÃ©taillÃ©e serait nÃ©cessaire.

OTHER : Cette colonne peut Ãªtre utilisÃ©e pour indiquer toute autre condition oculaire qui ne rentre pas dans les catÃ©gories spÃ©cifiques Ã©numÃ©rÃ©es ci-dessus.

In [16]:
df.isnull().sum()

ID        0
DR        0
NORMAL    0
MH        0
ODC       0
TSLN      0
ARMD      0
DN        0
MYA       0
BRVO      0
ODP       0
CRVO      0
CNV       0
RS        0
ODE       0
LS        0
CSR       0
HTR       0
ASR       0
CRS       0
OTHER     0
dtype: int64

#### The dataset contains no null values we can use it for our analysis. It still has string values but it's okay because we need to do a NLP analysis.